version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  test:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          command: node --version
      - run:
          command: npm --version
      - run:
          command: npm run test
      - store_test_results:
          path: /tmp/test-results/testcafe/results.xml
workflows:
  e2e-test:
    jobs:
      - test
